import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/main.scss";
import { ClientWrapper } from "./ClientWrapper";
import { ReduxProvider } from "../redux/ReduxProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} layout-body`}>
        <ReduxProvider>
          <div className="layout-wrapper">
            <ClientWrapper>{children}</ClientWrapper>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
