// app/layout.tsx
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ClientWrapper } from "./ClientWrapper";
import { ReduxProvider } from "../redux/ReduxProvider";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import CssBaseline from "@mui/material/CssBaseline";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} layout-body`}>
         <ReduxProvider>
          <CssBaseline />
          <ClientWrapper>{children}</ClientWrapper> 
        </ReduxProvider>
      </body>
    </html>
  );
}
